### ISSUE TITLE
Alterar texto "Code 4 Tuba" do reader pelo svg da logo

### ISSUE THREAD

**Issue by gefymarcos** [code4tuba/code4tuba.github.io#2]

**Comment by williangd** [comment]
Os svgs do code 4 tuba tem um espaço bem grande no top e bottom. Esse espaço existe por algum motivo?

**Comment by gefymarcos** [comment]
Eu tenho que exportar os svgs melhor, ta zuado mesmo, pode deixar essa pra issue pra mim
