### ISSUE TITLE
Formulário de contato, usar serviço de envio de e-mail

### ISSUE THREAD

**Issue by gefymarcos** [code4tuba/code4tuba.github.io#6]
Sugestão de usar o https://formcarry.com/

Precisamos criar um email de contato usando o dominio code4tuba, conhecem algum serviço de e-mail free? Eu usava a Umbler.

**Comment by williangd** [comment]
Já usei uma vez alguns serviços para envio de form em site estático, normalmente os planos free tem um limite de 100 envios mensais. Acho que não teria problema por agora.

Já usei esses dois:

https://formcarry.com
https://formspree.io/

Gostei mais do formcarry pq é mais simples, o formspree tinha que ficar verificando o e-mail.. talvez seja meio chato para o usuário, mas não sei se ainda continua assim.

Sobre os servidores de e-mail free: já ouvi falar do https://zoho.com e https://domain.yandex.com, mas nunca usei nenhum dos dois.

**Comment by gefymarcos** [comment]
Eu preferi usar o formcarry por conseguir deixar transparente pro usuário, o formspree redireciona pra uma página deles e tal, é meio estranho
