### ISSUE TITLE
Alterar icones do footer

### ISSUE THREAD

**Issue by gefymarcos** [code4tuba/code4tuba.github.io#7]
Linkar o instagram, twitter, github e slack do code for tuba

**Comment by LucasDNunes** [comment]
#10

**Comment by williangd** [comment]
@gefymarcos alguém ainda usa o slack do codefortuba? haha

**Comment by gefymarcos** [comment]
@williangd pois então kkkk acho que vamos deixar ele de lado por enquanto haha
